[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",       # missing docstring
    "D203",    # conflicts with D211 (blank line before class)
    "D205",    # noise
    "D213",    # conflicts with D212 (docstring summary position)
    "E501",    # line too long - ruff format is checked separately
    "COM812",  # formatter handles trailing commas
    "SIM112",  # lower case environment variables
    "PLR0911", # too many return statements
    "PLR0913", # too many arguments on function
    "FBT001","FBT002", # positional boolean
]

[tool.ruff.lint.per-file-ignores]
"main.py" = ["PLC0415"]   # allow import outside toplevel as not all modules need to be loaded for every function
"test/**/*.py" = ["S101"]

[tool.setuptools]
py-modules = []

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
default = true

[project]
name = "phaenonet-functions"
dynamic = ["version"]
requires-python = "==3.12.12"
dependencies = [
    "firebase-admin>=7.2.0",
    "numpy>=2.4.2",
    "dateparser>=1.3.0",
    "google-cloud-logging>=3.14.0",
    "sentry-sdk>=2.54.0",
    "jinja2>=3.1.6",
    "envelopes>=0.4",
    "tinify>=1.7.1",
    "google-cloud-secret-manager>=2.26.0",
    "flask>=3.1.3",
    "google-cloud-tasks>=2.21.0",
    "google-cloud-pubsub>=2.35.0",
    "google-cloud-bigquery>=3.40.1",
    "functions-framework>=3.10.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "pytest-cov>=7.0.0",
    "bandit>=1.9.4",
    "pytest-xprocess>=1.0.2",
    "strictyaml>=1.7.3",
    "tqdm>=4.67.3",
    "zizmor>=1.23.1",
    "actionlint-py>=1.7.11.24",
    "ruff>=0.15.22",
]
