name: deploy cloud functions

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project
        required: true
        default: phaenonet-test
        type: choice
        options:
          - phaenonet
          - phaenonet-test
      function:
        description: Function
        required: true
        type: choice
        options:
          # - all
          # - process_observation_activity
          # - process_observation_create_analytics
          # - process_observation_update_analytics
          # - process_observation_delete_analytics
          # - process_user
          # - process_invite
          # - process_invite_register
          # - import_wld_data
          # - import_meteoswiss_data
          # - export_meteoswiss_data
          # - create_thumbnails
          # - rollover_phenoyear
          # - process_ts_user
          # - process_ts_observation
          # - process_ts_individual
          # - process_ts_definitions
          # - process_ts_invite
          # - enqueue_individual_map
          # - process_individual_map
          # - process_dragino_http
          # - process_dragino_phaenonet
          # - process_dragino_bq
          # - process_dragino_permarobotics
          # - set_sensor
          # - promote_ranger
          # - test
          # - e2e_clear_individuals
      action:
        description: Action
        required: true
        default: deploy
        type: choice
        options:
          - deploy
          - undeploy
          - redeploy
      tag:
        description: Tag
        required: false
        type: string

env:
  RUNTIME: python39
  REGION: europe-west1
  TIMEOUT: 540s
  PROJECT: ${{ github.event.inputs.project }}
  FUNCTION: ${{ github.event.inputs.function }}
  ACTION: ${{ github.event.inputs.action }}
  TAG: ${{ github.event.inputs.tag }}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        include:
          - name: process_observation_activity
            entrypoint: process_observation_write_activity
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/observations/{observation_id}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: process_observation_create_analytics
            entrypoint: process_observation_create_analytics
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/observations/{observation_id}" --trigger-event providers/cloud.firestore/eventTypes/document.create
          - name: process_observation_update_analytics
            entrypoint: process_observation_update_analytics
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/observations/{observation_id}" --trigger-event providers/cloud.firestore/eventTypes/document.update
          - name: process_observation_delete_analytics
            entrypoint: process_observation_delete_analytics
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/observations/{observation_id}" --trigger-event providers/cloud.firestore/eventTypes/document.delete
          - name: process_user
            entrypoint: fs_users_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/users/{user_id}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: process_invite
            entrypoint: process_invite_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/invites/{invite_id}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: import_meteoswiss_data
            entrypoint: ps_import_meteoswiss_data_publish
            trigger: --trigger-resource import_meteoswiss_data --trigger-event google.pubsub.topic.publish
          - name: export_meteoswiss_data
            entrypoint: export_meteoswiss_data_manual
            trigger: --trigger-resource export_meteoswiss_data --trigger-event google.pubsub.topic.publish
          - name: process_new_files
            entrypoint: st_appspot_finalize
            trigger: --trigger-resource "$PROJECT.appspot.com" --trigger-event google.storage.object.finalize
          - name: rollover_phenoyear
            entrypoint: rollover_manual
            trigger: --trigger-resource rollover_phenoyear --trigger-event google.pubsub.topic.publish
          - name: process_ts_user
            entrypoint: fs_document_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/users/{document}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: process_ts_observation
            entrypoint: fs_document_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/observations/{document}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: process_ts_individual
            entrypoint: fs_document_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/individuals/{document}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: process_ts_definitions
            entrypoint: fs_document_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/definitions/{document}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: process_ts_invite
            entrypoint: fs_document_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/invites/{document}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: enqueue_individual_map
            entrypoint: enqueue_individual_map_write
            trigger: --trigger-resource "projects/$PROJECT/databases/(default)/documents/individuals/{document}" --trigger-event providers/cloud.firestore/eventTypes/document.write
          - name: process_individual_map
            entrypoint: process_individual_map_http
            trigger: --trigger-http
          - name: process_dragino_http
            entrypoint: process_dragino_http
            trigger: --trigger-http --allow-unauthenticated
          - name: process_dragino_phaenonet
            entrypoint: process_dragino_phaenonet
            trigger: --trigger-resource iot_dragino --trigger-event google.pubsub.topic.publish
          - name: process_dragino_bq
            entrypoint: process_dragino_bq
            trigger: --trigger-resource iot_dragino --trigger-event google.pubsub.topic.publish
          - name: process_dragino_permarobotics
            entrypoint: process_dragino_permarobotics
            trigger: --trigger-resource iot_dragino --trigger-event google.pubsub.topic.publish
          - name: set_sensor
            entrypoint: set_sensor_http
            trigger: --trigger-http
          - name: promote_ranger
            entrypoint: promote_ranger_http
            trigger: --trigger-http
          - name: test
            entrypoint: test
            trigger: --trigger-resource test --trigger-event google.pubsub.topic.publish
          - name: e2e_clear_individuals
            entrypoint: e2e_clear_user_individuals_http
            trigger: --trigger-http --allow-unauthenticated
            project: phaenonet-test
    env:
      VERSION: "${{ matrix.name }}@${{ github.event.inputs.tag && github.event.inputs.tag || github.sha }}"
    environment: ${{ github.event.inputs.project }}
    steps:
      - uses: actions/checkout@v3
      - name: Work around https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ env.PROJECT }}
      - name: set release version
        run: |
          echo "set release version: ${{ env.VERSION }}"
          sed -ri 's|"#VERSION#"|"${{ env.VERSION }}"|' env.*.yaml
      - name: undeploy
        run: gcloud functions delete ${{ matrix.name }} --region ${{ env.REGION }} --quiet
        if: ${{ (env.ACTION == 'undeploy' || env.ACTION == 'redeploy') && (matrix.name == env.FUNCTION || env.FUNCTION == 'all') && (matrix.project == env.PROJECT || matrix.project == null) }}
      - name: deploy
        run: gcloud functions deploy ${{ matrix.name }} --entry-point ${{ matrix.entrypoint }} --runtime ${{ env.RUNTIME }} ${{ matrix.trigger }} --timeout ${{ env.TIMEOUT }} --region ${{ env.REGION }} --quiet --env-vars-file env.${{ env.PROJECT }}.yaml
        if: ${{ (env.ACTION == 'deploy' || env.ACTION == 'redeploy') && (matrix.name == env.FUNCTION || env.FUNCTION == 'all') && (matrix.project == env.PROJECT || matrix.project == null) }}
      - name: Sentry release
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          echo "Create new release ${{ env.VERSION }}"
          sentry-cli releases new ${{ env.VERSION }}
          sentry-cli releases set-commits ${{ env.VERSION }} --auto
          sentry-cli releases finalize ${{ env.VERSION }}
          echo "Finalized release ${{ env.VERSION }}"
          echo "Adding deployment for ${{ env.ENVIRONMENT }} environment"
          sentry-cli releases deploys ${{ env.VERSION }} new --env ${{ env.ENVIRONMENT }}
        if: ${{ (env.ACTION == 'deploy' || env.ACTION == 'redeploy') && (matrix.name == env.FUNCTION || env.FUNCTION == 'all') && (matrix.project == env.PROJECT || matrix.project == null) }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: phaenonet
          SENTRY_PROJECT: phaenonet-functions
          ENVIRONMENT: ${{ env.PROJECT == 'phaenonet' && 'production' || 'test' }}
  tag:
    name: Tag
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.tag }}
    permissions:
      contents: write
    steps:
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ env.TAG }}
