name: Build and test

on: push

env:
  LANG: en_US.UTF-8
  UV_FROZEN: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  checks:
    permissions:
      contents: read # checkout
      pull-requests: write # reviewdog
    runs-on: ubuntu-24.04
    container: globeswiss/cloud-sdk:py3.12.12-554.0.0@sha256:3db9a24c68fdafd462600db739da909cbb17eca502828f4d3696a9c2d0484790
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - name: Sync dev dependencies
        run: uv sync
      - name: Check requirements file
        run: diff -w <(uv export --format requirements-txt --no-hashes --no-dev | grep '==') <(grep '==' requirements.txt)
      - name: Check bandit
        run: uv run bandit -r test phenoback main.py -c .bandit
        if: always()
      - name: Check pylint
        run: uv run pylint --reports=y phenoback test main.py
        if: always()
      - name: Check black
        uses: reviewdog/action-black@644053a260402bc4278a865906107bd8aef7fae8 # v3.22.4
        with:
          reporter: github-check
          verbose: True
          fail_on_error: True
        if: always()
      - name: Check markdownlint
        uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58 # v0.26.2
        with:
          reporter: github-check
          fail_level: warning
        if: always()
  test:
    permissions:
      id-token: write # codecov oidc
      contents: read # checkout
    runs-on: ubuntu-24.04
    container: globeswiss/cloud-sdk:py3.12.12-554.0.0@sha256:3db9a24c68fdafd462600db739da909cbb17eca502828f4d3696a9c2d0484790
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - name: Sync dev dependencies
        run: uv sync
      - name: Run pytest
        run: uv run python -m pytest --cov-report xml --cov=main --cov=phenoback --cov-branch
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          use_oidc: true
          files: ./coverage.xml
          flags: unittests
        if: always()
  zizmor:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      contents: read # only needed for private repos
      actions: read # only needed for private repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
